server:
  port: 8081
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest